version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wpdev
    volumes:
      - ./provision/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  wordpress:
    depends_on:
      - mysql
    build:
      context: ./provision/wordpress
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_PASSWORD: wpdev
    volumes:
      - webroot:/var/www/html
      - ./src/plugins/example:/var/www/html/wp-content/plugins/example
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 8082:80
  wp_cli:
    depends_on: 
      - mysql
      - wordpress
    image: wordpress:cli
    user: xfs # this user maps to www-data in the wordpress image
    volumes:
      - webroot:/var/www/html
      - ./src/plugins/example:/var/www/html/wp-content/plugins/example
  wordpress_phpunit:
    depends_on:
      - mysql_phpunit
    image: "chriszarate/wordpress-phpunit:6.0.6"
    environment:
      PHPUNIT_DB_HOST: "mysql_phpunit"
    volumes:
      - "./src:/app"
      - "testsuite:/tmp"
  mysql_phpunit:
    image: "mysql:5.7"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_test"
      MYSQL_ROOT_PASSWORD: ""
volumes:
  mysql-data: {}
  testsuite: {}
  webroot: {}